### ISSUE TITLE
Description 작성 필요합니다.

### ISSUE THREAD

**Issue by tocatoco** [ischoiiiii/myRoom#1]
**No description, website, or topics provided.**

로 표시됩니다. @ischoiiiii 

![image](https://cloud.githubusercontent.com/assets/12164502/25168310/005a3288-251e-11e7-9d51-5be0549107f3.png)

**Comment by ischoiiiii** [comment]
수정 완료했습니당! @tocatoco

**Comment by tocatoco** [comment]
이슈 Close
